// Generated by scripts/sync_initiative_kickoff_registry.py. DO NOT EDIT.
import type { InitiativeKickoffSource } from "./initiativeKickoffTemplates.ts";

export const GENERATED_INITIATIVE_KICKOFF_SOURCES: InitiativeKickoffSource[] = [
  {
    "directory": "078-knowledge-graphs",
    "plan": {
      "id": "078",
      "title": "Knowledge Graphs \u2014 Schema, Ontology & Graph Strategy",
      "status": "active",
      "primarySteward": "Systems Steward",
      "planPath": "research/078-knowledge-graphs/PLAN.md"
    },
    "kickoff": {
      "enabled": true,
      "initiativeId": null,
      "templateId": "initiative-078-kickoff",
      "label": "078 kickoff approval",
      "description": "Request steward approval for the Initiative 078 knowledge graph kickoff.",
      "objective": "Load the initiative 078 graph kickoff as a reusable task that preserves routing context, surfaces bottlenecks early, and keeps execution governed.",
      "agentRole": "research-architect",
      "requiredCapabilities": [
        "research-analysis",
        "schema-registry",
        "ontology-design",
        "graph-query-contracts",
        "retrieval-governance"
      ],
      "referencePaths": [
        "research/078-knowledge-graphs/DECISIONS.md",
        "research/078-knowledge-graphs/CHECKLIST.md",
        "research/reference/analysis/trustgraph.md",
        "research/reference/analysis/trustgraph_capability_matrix.md"
      ],
      "requiredTasks": [
        "Read the initiative plan, decisions, checklist, and TrustGraph reference analysis.",
        "Audit existing JSON schema locations under `shared/standards/` and verify the current registry story.",
        "Draft the M21 schema registry index without moving files yet.",
        "Define the minimal ontology scope for `Space`, `Contribution`, `Capability`, `Relation`, and `ProvenanceScope`.",
        "Specify the `KnowledgeBundle` manifest fields and retrieval policy contract.",
        "Prototype the read-only triple facade only after the registry and ontology shape are clear.",
        "Keep GraphRAG gated until ingestion and cross-index quality checks are green."
      ],
      "successCriteria": [
        "A planner/router can parse the emitted context without schema changes.",
        "The kickoff task body exposes the objective, bottlenecks, and error signals.",
        "The launcher remains reusable for future initiatives through the same governed registry path."
      ],
      "bottleneckSignals": [
        "Schema inventory drift or missing registry ownership.",
        "Ontology scope expanding beyond the minimal Space/Contribution/Capability/Relation/Provenance set.",
        "Graph query work starting before the registry and ontology contracts are stable."
      ],
      "errorSignals": [
        "Files are moved before the schema index is in place.",
        "GraphRAG work starts without ingestion and cross-index validation.",
        "Task context is reduced to a one-line launcher without routing detail."
      ],
      "fallbackRoutes": [
        "Escalate to schema registry cleanup if the current layout is inconsistent.",
        "Pause and refine the ontology scope if the initial vocabulary grows too quickly.",
        "Return to the proposal/planner lane if execution dependencies are still ambiguous."
      ],
      "routingOptions": [],
      "approvalSummary": "Steward-backed kickoff approval for initiative 078 so the staged M21-M25 graph delivery stays governed before execution.",
      "approvalRationale": "This kickoff should not bypass stewardship. Approval confirms the schema-registry-first sequence, minimal ontology scope, read-only triple facade, and GraphRAG gating before execution.",
      "approvalMessage": null
    }
  },
  {
    "directory": "132-eudaemon-alpha-initiative",
    "plan": {
      "id": "132",
      "title": "Eudaemon Alpha - Institutional Agent Readiness Plan",
      "status": "active",
      "primarySteward": "Systems Steward",
      "planPath": "research/132-eudaemon-alpha-initiative/PLAN.md"
    },
    "kickoff": {
      "enabled": true,
      "initiativeId": null,
      "templateId": "initiative-132-kickoff",
      "label": "132 kickoff approval",
      "description": "Request steward approval for the Initiative 132 institutional agent kickoff.",
      "objective": "Load the Initiative 132 kickoff as a bounded, approval-first task that preserves the heap, closeout, workflow, and stewardship boundaries before execution starts.",
      "agentRole": "systems-architect",
      "requiredCapabilities": [
        "heap-governance",
        "workflow-orchestration",
        "institutional-agent-architecture",
        "closeout-ledgers",
        "steward-review"
      ],
      "referencePaths": [
        "research/132-eudaemon-alpha-initiative/WORK_PRIMITIVES_ARCHITECTURE.md",
        "research/132-eudaemon-alpha-initiative/README.md",
        "research/124-polymorphic-heap-mode/PLAN.md",
        "research/126-agent-harness-architecture/PLAN.md",
        "research/130-space-capability-graph-governance/PLAN.md",
        "research/134-hybrid-workflow-authority-and-execution/PLAN.md"
      ],
      "requiredTasks": [
        "Read the Initiative 132 plan, README, and work-primitives architecture notes.",
        "Confirm the boundary stack: heap for exploratory work, closeout ledgers for follow-through, workflow artifacts for executable plans, and initiatives for governed architecture intent.",
        "Identify the first bounded kickoff slice for 132 without inventing a bespoke Eudaemon-only task or workspace primitive.",
        "Map the required integration touchpoints across heap promotion, stewardship feedback, closeout linkage, and workflow-backed promotion paths.",
        "Surface any policy or dependency ambiguity that should be routed to proposal generation or steward escalation before direct execution."
      ],
      "successCriteria": [
        "The kickoff task clearly preserves the initiative-versus-runtime primitive boundary.",
        "The router can decide whether 132 should go direct, proposal-first, or back to steward review.",
        "The kickoff does not imply autonomous promotion or a bespoke Eudaemon-only execution path."
      ],
      "bottleneckSignals": [
        "The kickoff starts treating the initiative plan as an executable workflow artifact.",
        "A new Eudaemon-specific task primitive or workspace abstraction is introduced.",
        "Dependencies on 124, 126, 130, or 134 are still too ambiguous for a bounded first slice."
      ],
      "errorSignals": [
        "Heap notes, closeout tasks, workflow checkpoints, and initiative artifacts are collapsed into one primitive.",
        "The kickoff bypasses steward review for structural or promotion-level decisions.",
        "The first slice assumes direct graph mutation or auto-promotion from exploratory outputs."
      ],
      "fallbackRoutes": [
        "Escalate to proposal generation if the first bounded slice still has multiple viable implementation paths.",
        "Escalate to steward review if the heap, workflow, or closeout boundaries are still disputed.",
        "Pause the kickoff if the work still depends on unresolved 124/126/130/134 interface decisions."
      ],
      "routingOptions": [],
      "approvalSummary": "Steward-backed kickoff approval for initiative 132 before any institutional-agent execution work is emitted.",
      "approvalRationale": "This kickoff should confirm the heap, closeout, workflow, and initiative boundaries before Eudaemon execution begins. Approval keeps Initiative 132 aligned to governed primitives rather than inventing a bespoke runtime path.",
      "approvalMessage": null
    }
  }
];
