#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_adapter;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_event_projector;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_event_sink;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_meta_policy;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_metrics;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_permission_ledger;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_protocol;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod acp_session_store;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod agent_evaluation_loop;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod agent_execution_events;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod agent_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod artifact_collab_crdt;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod auth_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod authz;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod brand_policy;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod capabilities_scanner;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod console_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod cortex_ux;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod cortex_ux_store;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod dfx_client;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod dpub_workbench_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod file_system_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod gateway_config;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod github_mcp_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod governance_client;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod heap_mapper;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod heap_nesting;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod ic_client;
pub mod knowledge_graph_query;
pub mod knowledge_graph_retrieval;
pub mod knowledge_graph_runtime;
pub mod knowledge_graph_service;
pub mod knowledge_graph_topology;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod lint_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod llm_adapter;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod local_connection;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod local_gateway;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod local_gateway_bridge;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod mcp;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod meta_harness_evaluator;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod meta_harness_store;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod motoko_graph_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod ops_agents;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod ops_artifacts;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod ops_flows;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod ops_gates;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod provider_probe;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod provider_runtime;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod resilience_service;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "siq-service-client"))]
pub mod siq_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod siq_types;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod snapshot_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod space_auditor;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod steward_gate;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod storage_adapter;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod streaming_transport;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod system_logs;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod telemetry_stream;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod terminal_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod testing_service;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod theme_policy;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod unified_config;
#[cfg(all(not(feature = "knowledge-graph-tests"), feature = "service-scaffolds"))]
pub mod version_manager;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod viewspec;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod viewspec_learning;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod viewspec_synthesis;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod workbench_ux;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod workflow_engine_client;
#[cfg(not(feature = "knowledge-graph-tests"))]
pub mod workflow_executor;
