#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

try:
    import tomllib
except Exception as exc:
    print(f"FAIL: tomllib unavailable: {exc}")
    raise SystemExit(1)


def repo_root() -> Path:
    return Path(os.environ.get("NOSTRA_WORKSPACE_ROOT", Path(__file__).resolve().parents[1]))


def read_frontmatter(path: Path) -> dict[str, object]:
    raw = path.read_text(encoding="utf-8")
    if not raw.startswith("---\n"):
        return {}
    end = raw.find("\n---", 4)
    if end == -1:
        return {}
    frontmatter = raw[4:end]

    def read_scalar(key: str) -> str:
        match = re.search(rf"(?m)^\s*{re.escape(key)}\s*:\s*(.+?)\s*$", frontmatter)
        if not match:
            return ""
        return match.group(1).strip().strip('"').strip("'")

    primary_steward = ""
    stewardship_match = re.search(
        r"(?ms)^\s*stewardship:\s*\n(?P<body>(?:[ \t]+.+\n)+)",
        frontmatter,
    )
    if stewardship_match:
        body = stewardship_match.group("body")
        steward_match = re.search(r"(?m)^[ \t]+primary_steward:\s*(.+?)\s*$", body)
        if steward_match:
            primary_steward = steward_match.group(1).strip().strip('"').strip("'")

    return {
        "id": read_scalar("id"),
        "title": read_scalar("title"),
        "status": read_scalar("status"),
        "primarySteward": primary_steward or None,
    }


def build_sources(root: Path) -> list[dict[str, object]]:
    research_root = root / "research"
    sources: list[dict[str, object]] = []

    for kickoff_path in sorted(research_root.glob("[0-9][0-9][0-9]-*/KICKOFF.toml")):
        directory = kickoff_path.parent.relative_to(research_root).as_posix()
        plan_path = kickoff_path.parent / "PLAN.md"
        kickoff = tomllib.loads(kickoff_path.read_text(encoding="utf-8"))
        plan = read_frontmatter(plan_path) if plan_path.exists() else {}
        sources.append(
            {
                "directory": directory,
                "plan": {
                    "id": str(plan.get("id", "")).strip(),
                    "title": str(plan.get("title", "")).strip(),
                    "status": str(plan.get("status", "")).strip(),
                    "primarySteward": plan.get("primarySteward"),
                    "planPath": f"research/{directory}/PLAN.md",
                }
                if plan_path.exists()
                else None,
                "kickoff": {
                    "enabled": bool(kickoff.get("enabled", False)),
                    "initiativeId": str(kickoff.get("initiative_id", "")).strip() or None,
                    "templateId": str(kickoff.get("template_id", "")).strip() or None,
                    "label": str(kickoff.get("label", "")).strip() or None,
                    "description": str(kickoff.get("description", "")).strip() or None,
                    "objective": str(kickoff.get("objective", "")).strip() or None,
                    "agentRole": str(kickoff.get("agent_role", "")).strip() or None,
                    "requiredCapabilities": [str(value).strip() for value in kickoff.get("required_capabilities", [])],
                    "referencePaths": [str(value).strip() for value in kickoff.get("reference_paths", [])],
                    "requiredTasks": [str(value).strip() for value in kickoff.get("required_tasks", [])],
                    "successCriteria": [str(value).strip() for value in kickoff.get("success_criteria", [])],
                    "bottleneckSignals": [str(value).strip() for value in kickoff.get("bottleneck_signals", [])],
                    "errorSignals": [str(value).strip() for value in kickoff.get("error_signals", [])],
                    "fallbackRoutes": [str(value).strip() for value in kickoff.get("fallback_routes", [])],
                    "routingOptions": kickoff.get("routing_options", []),
                    "approvalSummary": str(kickoff.get("approval_summary", "")).strip() or None,
                    "approvalRationale": str(kickoff.get("approval_rationale", "")).strip() or None,
                    "approvalMessage": str(kickoff.get("approval_message", "")).strip() or None,
                },
            }
        )

    sources.sort(key=lambda row: str(((row.get("plan") or {}) if isinstance(row.get("plan"), dict) else {}).get("id", "")))
    return sources


def render_module(sources: list[dict[str, object]]) -> str:
    payload = json.dumps(sources, indent=2)
    return "\n".join(
        [
            "// Generated by scripts/sync_initiative_kickoff_registry.py. DO NOT EDIT.",
            'import type { InitiativeKickoffSource } from "./initiativeKickoffTemplates.ts";',
            "",
            f"export const GENERATED_INITIATIVE_KICKOFF_SOURCES: InitiativeKickoffSource[] = {payload};",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Cortex web initiative kickoff registry from research metadata.")
    parser.add_argument("--mode", choices=["write", "check", "print"], default="write")
    parser.add_argument(
        "--output",
        default="cortex/apps/cortex-web/src/components/heap/generatedInitiativeKickoffRegistry.ts",
    )
    args = parser.parse_args()

    root = repo_root()
    output_path = root / args.output
    expected = render_module(build_sources(root))

    if args.mode == "print":
        print(expected)
        return 0

    current = output_path.read_text(encoding="utf-8") if output_path.exists() else None
    if args.mode == "check":
        if current != expected:
            print(f"FAIL: initiative kickoff registry is out of date: {output_path.relative_to(root)}")
            return 1
        print("PASS: initiative kickoff registry is synchronized")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"WROTE: {output_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
