#!/usr/bin/env python3
"""Dry-run CLI DispatchTransportAdapterV1 for WorkRouter outbox envelopes."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import jsonschema

from work_router_paths import work_router_log_root


ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "research" / "132-eudaemon-alpha-initiative"
ENVELOPE_SCHEMA = BASE / "schemas" / "DispatchTransportEnvelopeV1.schema.json"
DECISION_SCHEMA = BASE / "schemas" / "DispatchDecisionV1.schema.json"
ADAPTER_SCHEMA = BASE / "schemas" / "DispatchTransportAdapterV1.schema.json"
ADAPTER_FIXTURE = BASE / "examples" / "dispatch_transport_adapter_cli_dry_run.v1.json"
DEFAULT_OUTBOX = work_router_log_root() / "outbox"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def validate_adapter() -> None:
    jsonschema.validate(load_json(ADAPTER_FIXTURE), load_json(ADAPTER_SCHEMA))


def envelope_paths(outbox: Path, run_id: str | None) -> list[Path]:
    if run_id:
        return [outbox / f"{run_id}.json"]
    return sorted(outbox.glob("*.json"))


def load_envelope(path: Path) -> dict:
    envelope = load_json(path)
    jsonschema.validate(envelope, load_json(ENVELOPE_SCHEMA))
    if envelope["transport"]["kind"] != "cli":
        raise ValueError(f"{path}: CLI adapter cannot send transport kind {envelope['transport']['kind']}")
    return envelope


def print_envelope(envelope: dict) -> None:
    sys.stdout.write(f"== {envelope['envelopeId']} ==\n")
    sys.stdout.write(envelope["message"]["body"])
    if not envelope["message"]["body"].endswith("\n"):
        sys.stdout.write("\n")


def validate_decision(decision_path: Path, envelope: dict) -> dict:
    decision = load_json(decision_path)
    jsonschema.validate(decision, load_json(DECISION_SCHEMA))
    if decision["requestId"] != envelope["requestId"]:
        raise ValueError(
            f"{decision_path}: decision requestId {decision['requestId']} does not match envelope requestId {envelope['requestId']}"
        )
    return decision


def apply_decision(run_id: str, decision_path: Path) -> str:
    command = [
        "bash",
        str(ROOT / "scripts" / "work_router_apply_run_decision.sh"),
        "--run-id",
        run_id,
        "--decision",
        str(decision_path),
    ]
    completed = subprocess.run(command, cwd=ROOT, check=True, text=True, capture_output=True)
    return completed.stdout.strip()


def write_receipt(envelope: dict, outbox: Path, status: str) -> Path:
    receipt = {
        "schemaVersion": "1.0.0",
        "receiptId": f"cli-adapter-receipt:{envelope['runId']}",
        "envelopeId": envelope["envelopeId"],
        "runId": envelope["runId"],
        "requestId": envelope["requestId"],
        "transport": envelope["transport"],
        "status": status,
        "recordedAt": utc_now(),
    }
    # Adapter receipts are intentionally adapter-local; DispatchTransportReceiptV1 remains
    # the canonical request delivery receipt generated by the router.
    target = outbox / f"{envelope['runId']}.adapter-receipt.json"
    target.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    return target


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outbox", default=str(DEFAULT_OUTBOX))
    parser.add_argument("--run-id")
    parser.add_argument("--decision", help="Optional DispatchDecisionV1 file to apply after sending one envelope")
    parser.add_argument("--send", action="store_true", help="Print envelope message(s) to stdout")
    args = parser.parse_args(argv[1:])

    validate_adapter()
    outbox = Path(args.outbox)
    if not outbox.is_absolute():
        outbox = ROOT / outbox

    paths = envelope_paths(outbox, args.run_id)
    if not paths:
        json.dump({"sent": [], "count": 0}, sys.stdout, indent=2)
        sys.stdout.write("\n")
        return 0

    sent = []
    for path in paths:
        if not path.exists():
            continue
        envelope = load_envelope(path)
        if args.send:
            print_envelope(envelope)
        receipt_path = write_receipt(envelope, outbox, "sent")
        applied_run = None
        if args.decision:
            if len(paths) != 1:
                raise ValueError("--decision requires exactly one envelope; pass --run-id")
            decision_path = Path(args.decision)
            if not decision_path.is_absolute():
                decision_path = ROOT / decision_path
            validate_decision(decision_path, envelope)
            applied_run = apply_decision(envelope["runId"], decision_path)
        sent.append(
            {
                "runId": envelope["runId"],
                "envelope": str(path),
                "adapterReceipt": str(receipt_path),
                "appliedRun": applied_run,
            }
        )

    json.dump({"sent": sent, "count": len(sent)}, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
