use super::types::{ActivityStatus, LabManifest, LabStatus, contexts};

pub fn get_lab_registry() -> Vec<LabManifest> {
    vec![
        LabManifest {
            id: "labs:library".to_string(),
            name: "Nostra Library".to_string(),
            description: "Prototype of the system-wide Library app. Browse and read Core Books (GDPR Standard, Manifesto).".to_string(),
            version: "0.2.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/library".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can compliance policies be embedded directly into human-readable books as executable primitives?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-22T17:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:d3-graph".to_string(),
            name: "D3 Graph Explorer".to_string(),
            description: "Interactive data visualization playground using D3.js. Test physics and layout algorithms on your graph data.".to_string(),
            version: "0.4.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/d3".to_string()),
            status: LabStatus::Beta,
            supported_contexts: vec![
                contexts::CORTEX_GRAPH_TAB.to_string(),
                contexts::SPACES_NETWORK_VIEW.to_string(),
            ],
            hypothesis: "Can physics-based graph layouts reveal hidden patterns in knowledge networks?".to_string(),
            activity_status: ActivityStatus::Dormant,
            last_activity: "2026-01-10T12:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:compliance-validator".to_string(),
            name: "Compliance Validator".to_string(),
            description: "Validate compliance policies (GDPR, HIPAA, SOC 2) against Workflows and Spaces.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/compliance".to_string()),
            status: LabStatus::Alpha,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can policy constraints be validated automatically before workflow execution?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-22T14:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:ui-studio".to_string(),
            name: "UI Studio".to_string(),
            description: "AG-UI Protocol Playground. Edit JSON, preview components, and test Agent-Generated UIs.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/ui-studio".to_string()),
            status: LabStatus::Beta,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can agents generate production-quality UIs from declarative JSON schemas?".to_string(),
            activity_status: ActivityStatus::Dormant,
            last_activity: "2026-01-15T09:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:components".to_string(),
            name: "UI Components".to_string(),
            description: "Interactive Living Style Guide & Component Library. View and test all UI elements.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/components".to_string()),
            status: LabStatus::Beta,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can a living style guide reduce UI inconsistency across agent-generated interfaces?".to_string(),
            activity_status: ActivityStatus::Dormant,
            last_activity: "2026-01-12T16:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:data-viewer".to_string(),
            name: "Data Viewer".to_string(),
            description: "Table-based view of all entities and relationships in the knowledge graph.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/data".to_string()),
            status: LabStatus::Beta,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can tabular views make graph data more accessible to non-technical users?".to_string(),
            activity_status: ActivityStatus::Archived,
            last_activity: "2025-12-20T08:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:hrm-scheduler".to_string(),
            name: "HRM Scheduler".to_string(),
            description: "Prototype interface for the Hierarchical Reasoning Model scheduler adapter.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/scheduler".to_string()),
            status: LabStatus::Alpha,
            supported_contexts: vec![
                contexts::CORTEX_LABS.to_string(),
            ],
            hypothesis: "Can we visualize and control hierarchical agent reasoning in real-time?".to_string(),
            activity_status: ActivityStatus::Archived,
            last_activity: "2025-12-15T10:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:agent-libraries".to_string(),
            name: "Agent Tools Library".to_string(),
            description: "Enables agents to mount specialized tool sets (libraries) into their context for enhanced capabilities.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: None,
            status: LabStatus::Alpha,
            supported_contexts: vec![
                contexts::AGENT_CHAT.to_string(),
            ],
            hypothesis: "Can modular tool libraries reduce agent context pollution?".to_string(),
            activity_status: ActivityStatus::Dormant,
            last_activity: "2026-01-08T11:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:a2ui".to_string(),
            name: "A2UI Rendering".to_string(),
            description: "Experimental renderer for Agent-to-User Interfaces. Allows agents to stream dynamic UI components.".to_string(),
            version: "0.0.1".to_string(),
            thumbnail_url: None,
            route_path: None,
            status: LabStatus::Experimental,
            supported_contexts: vec![
                contexts::AGENT_CHAT.to_string(),
            ],
            hypothesis: "Can agents describe UIs as streams rather than complete documents?".to_string(),
            activity_status: ActivityStatus::Dormant,
            last_activity: "2026-01-05T14:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:map".to_string(),
            name: "Location Services".to_string(),
            description: "Geospatial context visualization and validation lab.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/map".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can location context enhance agent decision making without compromising privacy?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-23T12:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:benchmark-runner".to_string(),
            name: "Benchmark Runner".to_string(),
            description: "Execute and visualize AI Agent benchmarks (e.g., GAIA). Verify policy compliance and performance.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/benchmark".to_string()),
            status: LabStatus::Alpha,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can we deterministically measure agent capability and safety compliance?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-23T12:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:attested".to_string(),
            name: "Attested Lab (Phase 1)".to_string(),
            description: "Pilot for ZK-integrated gating. Verifies 'Proof Capabilities' using cryptographic signatures (Level 0).".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/attested".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can we gate access to sovereign spaces using async-verified cryptographic proofs?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-24T02:30:00Z".to_string(),
        },
        LabManifest {
            id: "labs:zk".to_string(),
            name: "ZK Trust Lab (Phase 2)".to_string(),
            description: "Advanced ZK-integrated gating using zCloak. Verifies 'Linked-but-Private' membership using PLONK proofs.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/zk".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can ZK proofs provide perfect privacy while maintaining interconnected trust in sovereign spaces?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-24T05:30:00Z".to_string(),
        },
        LabManifest {
            id: "labs:media".to_string(),
            name: "Media Lab".to_string(),
            description: "Nostra Media Engine & Timeline Studio. Native Rust-based high-performance video generation.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/media".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can we achieve Remotion-level DX and performance using pure Rust and Dioxus?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-24T06:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:workflow".to_string(),
            name: "Workflow Engine".to_string(),
            description: "Durable Workflow Engine control panel. Start flows and manage user tasks.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/workflow".to_string()),
            status: LabStatus::Alpha,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can we manage complex distributed state with a simple durable execution model?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-24T18:00:00Z".to_string(),
        },
        LabManifest {
            id: "labs:tempo".to_string(),
            name: "Tempo Lab".to_string(),
            description: "Temporal Strategy control plane. Audit V1 Readiness and monitor semantic activities.".to_string(),
            version: "0.1.0".to_string(),
            thumbnail_url: None,
            route_path: Some("/labs/tempo".to_string()),
            status: LabStatus::Prototype,
            supported_contexts: vec![contexts::CORTEX_LABS.to_string()],
            hypothesis: "Can high-level 'Ecosystem Readiness' be modeled as a verifiable temporal state?".to_string(),
            activity_status: ActivityStatus::Active,
            last_activity: "2026-01-24T20:00:00Z".to_string(),
        },
    ]
}
